spring:
  profiles:
    active: dev
  # 出现404错误时, 直接抛出异常
  mvc:
    throw-exception-if-no-handler-found: true
  # 不要为工程中的资源文件建立映射
  resources:
    add-mappings: false
# swagger2管理平台扫描接口路径
controller_path: com.upsoft.intelligenteye.controller

---
server:
  port: 8080
spring:
  profiles: dev
  # 数据源和数据池配置
  datasource:
    druid:
      # 数据源基本配置
      url: jdbc:mysql://172.16.5.49:3306/demo?useSSL=false&characterEncoding=UTF-8
      driver-class-name: com.mysql.jdbc.Driver
      username: root
      password: 123456
      # 数据源其他配置
      initialSize: 5
      minIdle: 5
      maxActive: 20
      maxWait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      connection-properties: druid.stat.mergeSql=true; druid.stat.slowSqlMillis=500; config.decrypt=true
      filters: stat,wall,slf4j,config
      # Spring监控配置，说明请参考Druid Github Wiki，pring监控AOP切入点，如x.y.z.service.*,配置多个英文逗号分隔
      aop-patterns: com.upsoft.intelligenteye.service.*
      # WebStatFilter和StatViewServlet配置，说明请参考Druid Wiki
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      web-stat-filter:
        enabled: true
        url-pattern: /*
        # exclusions配置第一个不能以*开头否则报错
        exclusions: /druid/*,*.js,*.gif,*.jpg,*.png,*.css,*.ico
        session-stat-enable: false
        session-stat-max-count: 1000
      stat-view-servlet:
        enabled: true
        # 配置druid监控登陆地址、登陆账号和密码
        url-pattern: /druid/*
        login-username: admin
        login-password: 123456
        reset-enable: true

# mybatis-plus配置
mybatis-plus:
  # 指定sql映射文件位置
  mapper-locations: classpath:mybatis/mapper/*.xml
  # 开启驼峰命名转换
  configuration:
    map-underscore-to-camel-case: true

---
server:
  port: 8084
spring:
  profiles: test


---
server:
  port: 8083
spring:
  profiles: prod